### ISSUE TITLE
Play button doesn't show up on Safari

### ISSUE THREAD

**Issue by 3lvis** [hyperoslo/grumbles-the-lame-wizard#25]
MacBook 15" Retina.

![screen shot 2014-10-19 at 11 12 45 pm](https://cloud.githubusercontent.com/assets/1088217/4694763/f0765e32-57d4-11e4-94f8-8495c4089270.png)

**Comment by sindrenm** [comment]
Make your screen thinner. Does it show up then?

**Comment by toothfairy** [comment]
Should I fix it to `top: 300px;` for .landing?

**Comment by toothfairy** [comment]
Instead of top 50%

**Comment by 3lvis** [comment]
Shrinking does this.

![screen shot 2014-10-19 at 11 18 40 pm](https://cloud.githubusercontent.com/assets/1088217/4694777/9224c46c-57d5-11e4-947e-c6e3036f1418.png)

**Comment by timkurvers** [comment]
My bad, I forgot to add the vendor prefixes. It's deployed, give it another shot.

**Comment by 3lvis** [comment]
Thanks <3 

![screen shot 2014-10-19 at 11 35 52 pm](https://cloud.githubusercontent.com/assets/1088217/4694820/f37f6b70-57d7-11e4-8b89-afdf432717a2.png)
